
#himanshukumarlenka
#Created New Year Countdown 2023 Using Javascript

<div class="wrapper">
    <div class="container text-center">
    <div class="col-md-12">
    <h1 id="header" class="">New Year Countdown</h1>
    </div>
    <div class="col-md-3 col-xs-6">
    <div class="clock">
    <div class="well top-pane">
    <div id="days" class="num">00</div>
    </div>
    <div class="well bottom-pane">
    <div id="days-text" class="text">Days</div>
    </div>
    </div>
    </div>
    <div class="col-md-3 col-xs-6">
    <div class="clock">
    <div class="well top-pane">
    <div id="hours" class="num">00</div>
    </div>
    <div class="well bottom-pane">
    <div id="hours-text" class="text">Hours</div>
    </div>
    </div>
    </div>
    <div class="col-md-3 col-xs-6">
    <div class="clock">
    <div class="well top-pane">
    <div id="mins" class="num">00</div>
    </div>
    <div class="well bottom-pane">
    <div id="mins-text" class="text">Minutes</div>
    </div>
    </div>
    </div>
    <div class="col-md-3 col-xs-6">
    <div class="clock">
    <div class="well top-pane">
    <div id="secs" class="num">00</div>
    </div>
    <div class="well bottom-pane">
    <div id="secs-text" class="text">Seconds</div>
    </div>
    </div>
    </div>
    <div id="info" class="small"></div>
    </div>
    </div>